# Generated by Django 3.0.2 on 2020-02-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='varify_password',
            new_name='verify_password',
        ),
    ]
