# Generated by Django 3.0.2 on 2020-02-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0003_auto_20200205_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verify_password',
        ),
    ]
