# Generated by Django 3.0.2 on 2020-02-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0006_auto_20200205_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uname',
            new_name='user',
        ),
    ]
