# Generated by Django 3.0.2 on 2020-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0009_basicinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
