# Generated by Django 3.0.2 on 2020-02-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0010_auto_20200206_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='projecttitle',
            new_name='project_title',
        ),
    ]
