# Generated by Django 3.0.2 on 2020-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0011_auto_20200206_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='collagename',
            new_name='collage_name',
        ),
        migrations.RenameField(
            model_name='basicinfo',
            old_name='compname',
            new_name='company_name',
        ),
    ]
