# Generated by Django 3.0.2 on 2020-02-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0012_auto_20200206_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='student',
        ),
    ]
