# Generated by Django 3.0.2 on 2020-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0013_remove_basicinfo_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='reportno',
        ),
    ]
