# Generated by Django 3.0.2 on 2020-02-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0014_remove_basicinfo_reportno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='pid',
            field=models.CharField(max_length=10),
        ),
    ]
