# Generated by Django 3.0.2 on 2020-02-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0015_auto_20200207_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reportapp.profile'),
            preserve_default=False,
        ),
    ]
