# Generated by Django 3.0.2 on 2020-02-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0016_basicinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='collage_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='project_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='basicinfo',
        ),
    ]
