# Generated by Django 3.0.2 on 2020-02-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0018_auto_20200207_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(max_length=1000)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportapp.topic')),
            ],
        ),
    ]
