# Generated by Django 3.0.2 on 2020-02-08 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0020_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
