# Generated by Django 3.0.2 on 2020-02-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0022_auto_20200208_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
