# Generated by Django 3.0.2 on 2020-02-08 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0023_auto_20200208_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtopic1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('subtopic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='topic1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportapp.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='subtopic',
        ),
        migrations.DeleteModel(
            name='topic',
        ),
        migrations.AddField(
            model_name='subtopic1',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportapp.topic1'),
        ),
        migrations.AddField(
            model_name='subtopic1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportapp.profile'),
        ),
    ]
