# Generated by Django 3.0.2 on 2020-02-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0026_auto_20200208_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic1',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reportapp.profile'),
            preserve_default=False,
        ),
    ]
