# Generated by Django 3.0.2 on 2020-02-11 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0028_auto_20200210_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic1',
            name='created_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
