# Generated by Django 3.0.2 on 2020-02-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0029_topic1_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic1',
            name='created_date',
        ),
    ]
