# Generated by Django 3.0.2 on 2020-02-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0033_subtopic1_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic1',
            name='week',
        ),
    ]
